### ISSUE TITLE
curiosity

### ISSUE THREAD

**Issue by cvega** [Facepunch/Rust.ModLoader#1]
I'm curious if you could expand on the `README` with a rudimentary example of how this could be used at a basic level. Super interested in this. Love the work y'all do.

**Comment by jamesalbert** [comment]
Yeah, this project looks awesome. I’d like to help where I can, but not sure where to start. A contributing doc would be really useful.

**Comment by Rohansi** [comment]
Somehow missed this. I've updated the readme a bit and added a contributing doc but it basically boils down to 'try it and lets talk about it'.

I just realized there's no instructions on how to set this up though. It's basically compile this, copy DLL and dependencies to HarmonyMods, put your C# scripts into Scripts folder. I'll write something proper up.

**Comment by jamesalbert** [comment]
@Rohansi thanks for the update on this. @cvega and I have been eyeing this repo pretty much since it was started. We're coming from a bit of a different background, but we're definitely interested in contributing.

I personally have a couple questions about the existing Update hook:

```cs
using System;
using Harmony;
using UnityEngine;

namespace Rust.ModLoader.Hooks.Server
{
    [HarmonyPatch(typeof(ServerMgr), "Update")]
    public class ServerUpdateHook
    {
        [HarmonyPostfix]
        public static void Postfix(ServerMgr __instance)
        {
            try
            {
                ModLoader.Scripts?.Update();
                ModLoader.Scripts?.Broadcast("Update");
            }
            catch (Exception e)
            {
                Debug.LogException(e);
            }
        }
    }
}
```

I'm interpreting this to mean that we're patching the ServerMgr.Update method to do the following after the original function call:
- call the ScriptManager.Update() to reload any scripts if need be
- call Broadcast in order to call the Update() method in all active scripts

Going off this example, I thought I'd start with a `PlayerSpawned` hook. The goal being: a player has just spawned on the server => call a corresponding `PlayerSpawned` method in all active scripts. This is what I came up with:

```cs
using System;
using Harmony;
using UnityEngine;

namespace Rust.ModLoader.Hooks.Server
{
    [HarmonyPatch(typeof(ServerMgr), "SpawnNewPlayer")]
    public class ServerPlayerSpawnedHook
    {
        [HarmonyPostfix]
        public static void Postfix(ServerMgr __instance, ref BasePlayer __result)
        {
            try
            {
                ModLoader.Scripts?.Broadcast("PlayerSpawned");
            }
            catch (Exception e)
            {
                Debug.LogException(e);
            }
        }
    }
}
```

Not too far off from `Update` , but nothing's being called when a player is spawned.  To this point, I tried patching various functions from ServerMgr, but the only ones that seem to trigger are Update and OnSteamConnected (at least from the ones I've tried). Are there certain conditions a function has to meet in order to be patched with Harmony? Or is there some scaffolding that I'm missing in the hook implementation?

Like you said, I'm sure you're busy working out more docs, but if you have time to give some insight here, that'd be awesome. Can't wait to see more of this project 👍 

ps: I would have posted this in the discussion page, but I'm not sure if you want to designate that for design / implementation discussion instead of general questions. Let me know!

**Comment by Rohansi** [comment]
It looks like that should work. Only thing to note is `SpawnNewPlayer` is only called when 1. a player connects to server and 2. the player is not sleeping (new to the server or dead).

A better candidate would be inside `BasePlayer`, the function `void PlayerInit(Network.Connection)`. this does all the initialization for players when they connect to the server (sleeper or not). However, respawns do not take this path, they use `BasePlayer` function `void RespawnAt(Vector3, Quaternion)`.

Let's move this to the discussions area. It auto-created sections for general, ideas, and Q&A so it seems appropriate. Issues are for known bugs or work to be completed.
